/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InventoryManager;
import Admin.Loginpage1;
import javax.swing.JFrame;

import InventoryManager.functions.InventoryService;
import model.Item;
import model.PurchaseOrder;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author reymy
 */
public class InventoryManagerDashboard extends javax.swing.JFrame {

    private String employeeID;
    private String position;
    /**
    /**
     * Creates new form InventoryManagerDashboard
     */
    public InventoryManagerDashboard(String identifier) {
        String[] parts = identifier.split(":");
        if (parts.length == 2) {
            this.employeeID = parts[0];
            this.position = parts[1];
        } else {
            this.employeeID = "Unknown";
            this.position = "Unknown";
            System.out.println("Error: LoggedInIdentifier has an unexpected format: [" + identifier + "]");
        }

        System.out.println("EmployeeID: " + employeeID);
        System.out.println("Position: " + position);
        
        setUndecorated(true);
        initComponents();
        // Update the label to show the actual user ID
        jLabel1.setText("Inventory Manager, " + this.employeeID);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        updateInventorySnapshot();
    }
    
    private void updateInventorySnapshot() {
        //  Reload latest inventory data after threshold updates
        List<model.Item> items = InventoryManager.functions.InventoryService.loadItemsFromFile("src/txtFile/items.txt");
        List<model.PurchaseOrder> poList = InventoryManager.functions.InventoryService.loadPOsFromFile("src/txtFile/po.txt");

        int totalItems = items.size();
        int lowStockCount = 0;
        for (model.Item item : items) {
            if (item.getTotalStock() < InventoryManager.functions.InventoryService.LOW_STOCK_THRESHOLD) {
                lowStockCount++;
            }
        }

        int pendingPOCount = 0;
        for (model.PurchaseOrder po : poList) {
            if (po.getStatus().equalsIgnoreCase("Pending")) {
                pendingPOCount++;
            }
        }

        // Refresh UI Labels
        totalItemsLabel.setText("Total Items in Stock: " + totalItems);
        lowStockLabel.setText("Items Low in Stock: " + lowStockCount);
        pendingPOsLabel.setText("Pending Purchase Orders: " + pendingPOCount);

        // Update timestamp for latest changes
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd MMM yyyy HH:mm:ss");
        String formattedDate = LocalDateTime.now().format(formatter);
        lastUpdatedLabel.setText("Last Updated: " + formattedDate);

        // Ensure threshold label reflects new threshold
        thresholdLabel.setText("Current Threshold: " + InventoryService.LOW_STOCK_THRESHOLD);
    }


    public void refreshInventorySnapshot() {
        updateInventorySnapshot(); // Calls the private method internally
    }

    
    //Use for testing only, simulate log in
    /*
    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(() -> {
            // Replace with a dummy identifier format expected by the constructor
            new InventoryManagerDashboard("1007:Inventory Manager").setVisible(true);
        });
    }
    */


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        viewItemsButton = new javax.swing.JButton();
        poVerificationButton = new javax.swing.JButton();
        lowStockAlertButton = new javax.swing.JButton();
        generateStockButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        snapshotTitleLabel = new javax.swing.JLabel();
        totalItemsLabel = new javax.swing.JLabel();
        lowStockLabel = new javax.swing.JLabel();
        pendingPOsLabel = new javax.swing.JLabel();
        lastUpdatedLabel = new javax.swing.JLabel();
        thresholdLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(197, 186, 255));

        viewItemsButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        viewItemsButton.setText("View Items");
        viewItemsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewItemsButtonActionPerformed(evt);
            }
        });

        poVerificationButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        poVerificationButton.setText("Purchase Order Verification");
        poVerificationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poVerificationButtonActionPerformed(evt);
            }
        });

        lowStockAlertButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lowStockAlertButton.setText("Low Stock Alerts");
        lowStockAlertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowStockAlertButtonActionPerformed(evt);
            }
        });

        generateStockButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        generateStockButton.setText("Generate Stock Report");
        generateStockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateStockButtonActionPerformed(evt);
            }
        });

        logoutButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewItemsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(poVerificationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lowStockAlertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generateStockButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(viewItemsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(poVerificationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lowStockAlertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(generateStockButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );

        jPanel5.setBackground(new java.awt.Color(232, 249, 255));

        welcomeLabel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel.setText("WELCOME BACK!");

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Inventory Manager, <userid>");

        jPanel1.setBackground(new java.awt.Color(196, 217, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        snapshotTitleLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        snapshotTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        snapshotTitleLabel.setText("Inventory Snapshot");

        totalItemsLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        totalItemsLabel.setText("Unique Items in Stock:");

        lowStockLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lowStockLabel.setText("Items Low in Stock:");

        pendingPOsLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pendingPOsLabel.setText("Pending Purchase Orders:");

        lastUpdatedLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lastUpdatedLabel.setText("Last Updated:");

        thresholdLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        thresholdLabel.setText("Current Low Stock Threshold: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(snapshotTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lowStockLabel)
                            .addComponent(totalItemsLabel)
                            .addComponent(pendingPOsLabel)
                            .addComponent(lastUpdatedLabel)
                            .addComponent(thresholdLabel))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(snapshotTitleLabel)
                .addGap(51, 51, 51)
                .addComponent(totalItemsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lowStockLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pendingPOsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lastUpdatedLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(thresholdLabel)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(welcomeLabel)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void viewItemsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewItemsButtonActionPerformed
        new ViewItems().setVisible(true);
        
    }//GEN-LAST:event_viewItemsButtonActionPerformed

    private void poVerificationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poVerificationButtonActionPerformed
        POVerification poVerification = new POVerification(this);
        poVerification.setVisible(true);
    }//GEN-LAST:event_poVerificationButtonActionPerformed

    private void lowStockAlertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowStockAlertButtonActionPerformed
        new LowStockAlert().setVisible(true);
        
    }//GEN-LAST:event_lowStockAlertButtonActionPerformed

    private void generateStockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateStockButtonActionPerformed
        new GenerateStockReport().setVisible(true);
        
    }//GEN-LAST:event_generateStockButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        int response = JOptionPane.showConfirmDialog(this, 
        "Are you sure you want to log out?", 
        "Logout Confirmation", 
        JOptionPane.YES_NO_OPTION, 
        JOptionPane.QUESTION_MESSAGE);

        // Check the user's response
        if (response == JOptionPane.YES_OPTION) {
            // Dispose the AdminTest frame
            this.dispose();

            // Open Loginpage1 frame
            Loginpage1 loginPage = new Loginpage1();
            loginPage.setVisible(true);
            loginPage.pack();
            loginPage.setLocationRelativeTo(null);
            loginPage.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        }
    }//GEN-LAST:event_logoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton generateStockButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lastUpdatedLabel;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton lowStockAlertButton;
    private javax.swing.JLabel lowStockLabel;
    private javax.swing.JLabel pendingPOsLabel;
    private javax.swing.JButton poVerificationButton;
    private javax.swing.JLabel snapshotTitleLabel;
    private javax.swing.JLabel thresholdLabel;
    private javax.swing.JLabel totalItemsLabel;
    private javax.swing.JButton viewItemsButton;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
