/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InventoryManager;
import javax.swing.JFrame;

import InventoryManager.functions.InventoryService;
import model.Item;
import model.PurchaseOrder;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

/**
 *
 * @author reymy
 */
public class InventoryManagerDashboard extends javax.swing.JFrame {

    private String employeeID;
    private String position;
    /**
    /**
     * Creates new form InventoryManagerDashboard
     */
    public InventoryManagerDashboard(String identifier) {
        String[] parts = identifier.split(":");
        if (parts.length == 2) {
            this.employeeID = parts[0];
            this.position = parts[1];
        } else {
            this.employeeID = "Unknown";
            this.position = "Unknown";
            System.out.println("Error: LoggedInIdentifier has an unexpected format: [" + identifier + "]");
        }

        System.out.println("EmployeeID: " + employeeID);
        System.out.println("Position: " + position);
        
        setUndecorated(true);
        initComponents();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        updateInventorySnapshot();
    }
    
    private void updateInventorySnapshot() {
        List<model.Item> items = InventoryManager.functions.InventoryService.loadItemsFromFile("src/txtFile/items.txt");
        List<model.PurchaseOrder> poList = InventoryManager.functions.InventoryService.loadPOsFromFile("src/txtFile/po.txt");

        int totalItems = items.size();
        int lowStockCount = 0;
        for (model.Item item : items) {
            if (item.getTotalStock() < InventoryManager.functions.InventoryService.LOW_STOCK_THRESHOLD) {
                lowStockCount++;
            }
        }

        int pendingPOCount = 0;
        for (model.PurchaseOrder po : poList) {
            if (po.getStatus().equalsIgnoreCase("Pending")) {
                pendingPOCount++;
            }
        }

        totalItemsLabel.setText("Total Items in Stock: " + totalItems);
        lowStockLabel.setText("Items Low in Stock: " + lowStockCount);
        pendingPOsLabel.setText("Pending Purchase Orders: " + pendingPOCount);
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd MMM yyyy HH:mm:ss");
        String formattedDate = LocalDateTime.now().format(formatter);
        lastUpdatedLabel.setText("Last Updated: " + formattedDate);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        viewItemsButton = new javax.swing.JButton();
        poVerificationButton = new javax.swing.JButton();
        lowStockAlertButton = new javax.swing.JButton();
        generateStockButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        closeButton = new javax.swing.JLabel();
        welcomeLabel = new javax.swing.JLabel();
        userIdLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        snapshotTitleLabel = new javax.swing.JLabel();
        totalItemsLabel = new javax.swing.JLabel();
        lowStockLabel = new javax.swing.JLabel();
        pendingPOsLabel = new javax.swing.JLabel();
        lastUpdatedLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(238, 201, 237));

        viewItemsButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        viewItemsButton.setText("View Items");
        viewItemsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewItemsButtonActionPerformed(evt);
            }
        });

        poVerificationButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        poVerificationButton.setText("Purchase Order Verification");
        poVerificationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poVerificationButtonActionPerformed(evt);
            }
        });

        lowStockAlertButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lowStockAlertButton.setText("Low Stock Alerts");
        lowStockAlertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowStockAlertButtonActionPerformed(evt);
            }
        });

        generateStockButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        generateStockButton.setText("Generate Stock Report");
        generateStockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateStockButtonActionPerformed(evt);
            }
        });

        logoutButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewItemsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(poVerificationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lowStockAlertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generateStockButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(viewItemsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(poVerificationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lowStockAlertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(generateStockButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );

        jPanel5.setBackground(new java.awt.Color(235, 247, 255));

        closeButton.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        closeButton.setText("X");
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonMouseClicked(evt);
            }
        });

        welcomeLabel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel.setText("WELCOME BACK!");

        userIdLabel.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        userIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userIdLabel.setText("Inventory Manager, <userid>");

        jPanel1.setBackground(new java.awt.Color(250, 230, 216));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        snapshotTitleLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        snapshotTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        snapshotTitleLabel.setText("Inventory Snapshot");

        totalItemsLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        totalItemsLabel.setText("Total Items in Stock:");

        lowStockLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lowStockLabel.setText("Items Low in Stock:");

        pendingPOsLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pendingPOsLabel.setText("Pending Purchase Orders:");

        lastUpdatedLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lastUpdatedLabel.setText("Last Updated:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(snapshotTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lowStockLabel)
                            .addComponent(totalItemsLabel)
                            .addComponent(pendingPOsLabel)
                            .addComponent(lastUpdatedLabel))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(snapshotTitleLabel)
                .addGap(51, 51, 51)
                .addComponent(totalItemsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lowStockLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pendingPOsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lastUpdatedLabel)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 34, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(closeButton)
                .addGap(29, 29, 29)
                .addComponent(welcomeLabel)
                .addGap(18, 18, 18)
                .addComponent(userIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewItemsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewItemsButtonActionPerformed
        new ViewItems().setVisible(true);
        dispose();
    }//GEN-LAST:event_viewItemsButtonActionPerformed

    private void poVerificationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poVerificationButtonActionPerformed
        this.setVisible(false);
        POVerification poVerification = new POVerification(this);
        poVerification.setVisible(true);
    }//GEN-LAST:event_poVerificationButtonActionPerformed

    private void lowStockAlertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowStockAlertButtonActionPerformed
        new LowStockAlert().setVisible(true);
        dispose();
    }//GEN-LAST:event_lowStockAlertButtonActionPerformed

    private void generateStockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateStockButtonActionPerformed
        new GenerateStockReport().setVisible(true);
        dispose();
    }//GEN-LAST:event_generateStockButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void closeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeButtonMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel closeButton;
    private javax.swing.JButton generateStockButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lastUpdatedLabel;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton lowStockAlertButton;
    private javax.swing.JLabel lowStockLabel;
    private javax.swing.JLabel pendingPOsLabel;
    private javax.swing.JButton poVerificationButton;
    private javax.swing.JLabel snapshotTitleLabel;
    private javax.swing.JLabel totalItemsLabel;
    private javax.swing.JLabel userIdLabel;
    private javax.swing.JButton viewItemsButton;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
