/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FinanceManager;

import FinanceManager.functions.ExportHelper;
import FinanceManager.functions.FinancialReportHelper;
import FinanceManager.functions.FinancialSummary;
import java.awt.Component;
import java.util.LinkedHashMap;

/**
 *
 * @author charl
 */
public class FinancialReport extends javax.swing.JFrame {

    /**
     * Creates new form FinancialReport
     */ 
    private LinkedHashMap<String, Integer> topItems;
    private Component previousComponent;
    
    public FinancialReport(Component previousComponent) {
        initComponents();
        this.previousComponent = previousComponent;
        FinancialSummary summary = FinancialReportHelper.loadSummary("src/txtFile/po.txt");

        TotalPO.setText(String.valueOf(summary.totalPO));
        TotalPayment.setText("RM " + String.format("%.2f", summary.totalPayment));
        OutstandingAmount.setText("RM " + String.format("%.2f", summary.outstandingAmount));
        PendingApprovals.setText(String.valueOf(summary.pendingApprovals));
        RejectedOrder.setText(String.valueOf(summary.rejectedOrders));

        topItems = FinancialReportHelper.getTopItems("src/txtFile/po.txt");
        ((BarChartPanel) barChartPanel).setData(topItems);

        comboMonthFilter.removeAllItems();
        comboMonthFilter.addItem("All Months");
        for (String month : FinancialReportHelper.extractMonths("src/txtFile/po.txt")) {
            comboMonthFilter.addItem(month);
        }

        
        comboMonthFilter.addActionListener(e -> applyMonthFilter());

    }

    private void applyMonthFilter() {
        String selected = (String) comboMonthFilter.getSelectedItem();
        if (selected == null) return;

        FinancialSummary summary = FinancialReportHelper.filterByMonth("src/txtFile/po.txt", selected);

        // Update UI
        TotalPO.setText(String.valueOf(summary.totalPO));
        TotalPayment.setText("RM " + String.format("%.2f", summary.totalPayment));
        OutstandingAmount.setText("RM " + String.format("%.2f", summary.outstandingAmount));
        PendingApprovals.setText(String.valueOf(summary.pendingApprovals));
        RejectedOrder.setText(String.valueOf(summary.rejectedOrders));

        topItems = summary.topItems;
        ((BarChartPanel) barChartPanel).setData(topItems);
        barChartPanel.repaint();
    }





    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        reportPanel = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        labelTotalPO = new javax.swing.JLabel();
        TotalPO = new javax.swing.JLabel();
        labelTotalPayment = new javax.swing.JLabel();
        TotalPayment = new javax.swing.JLabel();
        labelPendingApproval = new javax.swing.JLabel();
        PendingApprovals = new javax.swing.JLabel();
        labelRejectedOrders = new javax.swing.JLabel();
        OutstandingAmount = new javax.swing.JLabel();
        labelOutstandingAmount = new javax.swing.JLabel();
        RejectedOrder = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelTopPurchasedItems = new javax.swing.JLabel();
        barChartPanel = new BarChartPanel(null);
        exit = new javax.swing.JLabel();
        btnGenerate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        comboMonthFilter = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(251, 255, 241));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.setPreferredSize(new java.awt.Dimension(799, 599));

        reportPanel.setBackground(new java.awt.Color(255, 226, 226));
        reportPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        labelTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Icon - report title.png"))); // NOI18N
        labelTitle.setText("Financial Report");

        labelTotalPO.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTotalPO.setText("Total Purchase Order: ");

        TotalPO.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TotalPO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        labelTotalPayment.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTotalPayment.setText("Total Payment: ");

        TotalPayment.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TotalPayment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        labelPendingApproval.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelPendingApproval.setText("Pending Approvals: ");

        PendingApprovals.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PendingApprovals.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        labelRejectedOrders.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelRejectedOrders.setText("Rejected Orders: ");

        OutstandingAmount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        OutstandingAmount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        labelOutstandingAmount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelOutstandingAmount.setText("Outstanding Amount: ");

        RejectedOrder.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RejectedOrder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jPanel2.setBackground(new java.awt.Color(255, 226, 226));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        labelTopPurchasedItems.setText("Top 3 Purchased Items (By Quantity):");

        barChartPanel.setMaximumSize(new java.awt.Dimension(300, 140));

        javax.swing.GroupLayout barChartPanelLayout = new javax.swing.GroupLayout(barChartPanel);
        barChartPanel.setLayout(barChartPanelLayout);
        barChartPanelLayout.setHorizontalGroup(
            barChartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );
        barChartPanelLayout.setVerticalGroup(
            barChartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(barChartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelTopPurchasedItems, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                        .addGap(139, 139, 139)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTopPurchasedItems)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barChartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout reportPanelLayout = new javax.swing.GroupLayout(reportPanel);
        reportPanel.setLayout(reportPanelLayout);
        reportPanelLayout.setHorizontalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reportPanelLayout.createSequentialGroup()
                        .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(reportPanelLayout.createSequentialGroup()
                                .addComponent(labelRejectedOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RejectedOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(reportPanelLayout.createSequentialGroup()
                                .addComponent(labelPendingApproval, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PendingApprovals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(reportPanelLayout.createSequentialGroup()
                                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelOutstandingAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelTotalPO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TotalPayment, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TotalPO, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                    .addComponent(OutstandingAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(labelTotalPayment))
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reportPanelLayout.createSequentialGroup()
                        .addComponent(labelTitle)
                        .addGap(89, 89, 89))))
        );
        reportPanelLayout.setVerticalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(labelTitle)
                .addGap(35, 35, 35)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTotalPO)
                    .addComponent(TotalPO, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reportPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(labelTotalPayment)
                        .addGap(18, 18, 18)
                        .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reportPanelLayout.createSequentialGroup()
                                .addComponent(labelOutstandingAmount)
                                .addGap(18, 18, 18))
                            .addGroup(reportPanelLayout.createSequentialGroup()
                                .addComponent(OutstandingAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPendingApproval)
                            .addComponent(PendingApprovals, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(reportPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(TotalPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelRejectedOrders)
                    .addComponent(RejectedOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        exit.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        exit.setText("X");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });

        btnGenerate.setBackground(new java.awt.Color(255, 226, 226));
        btnGenerate.setText("Export Report");
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(255, 255, 204));
        btnCancel.setForeground(new java.awt.Color(51, 51, 51));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        comboMonthFilter.setBackground(new java.awt.Color(255, 207, 207));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(157, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(comboMonthFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(btnGenerate)
                        .addGap(72, 72, 72)
                        .addComponent(btnCancel)
                        .addGap(162, 162, 162))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(reportPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111)))
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exit)
                .addContainerGap(574, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(reportPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerate)
                    .addComponent(btnCancel)
                    .addComponent(comboMonthFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(800, 625));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        this.dispose();
         if (previousComponent != null) {
            previousComponent.setVisible(true);
        }
    }//GEN-LAST:event_exitMouseClicked

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
         if (previousComponent != null) {
            previousComponent.setVisible(true);
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        // TODO add your handling code here:
        FinancialReportFormat dialog = new FinancialReportFormat(this, true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);

        String format = dialog.getSelectedFormat();
        if (format == null) return;

        if (format.equals("PDF")) {
            ExportHelper.exportToPDF(reportPanel, this);
        } else if (format.equals("PNG")) {
            ExportHelper.exportToPNG(reportPanel, this);
        }
    }//GEN-LAST:event_btnGenerateActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel OutstandingAmount;
    private javax.swing.JLabel PendingApprovals;
    private javax.swing.JLabel RejectedOrder;
    private javax.swing.JLabel TotalPO;
    private javax.swing.JLabel TotalPayment;
    private javax.swing.JPanel barChartPanel;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnGenerate;
    private javax.swing.JComboBox<String> comboMonthFilter;
    private javax.swing.JLabel exit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelOutstandingAmount;
    private javax.swing.JLabel labelPendingApproval;
    private javax.swing.JLabel labelRejectedOrders;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelTopPurchasedItems;
    private javax.swing.JLabel labelTotalPO;
    private javax.swing.JLabel labelTotalPayment;
    private javax.swing.JPanel reportPanel;
    // End of variables declaration//GEN-END:variables
}
