/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import Admin.functions.RegisterManager;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Employee;
/**
 *
 * @author ELYSHA SOPHIA
 */
public class Registerpage extends javax.swing.JFrame {
    
    private RegisterManager registerManager;
    private String employeeID;
    private String position;

    public Registerpage(String identifier) {
        registerManager = new RegisterManager(); // Initialize backend

        String[] parts = identifier.split(":");
        if (parts.length == 2) {
            this.employeeID = parts[0];
            this.position = parts[1];
        } else {
            this.employeeID = "Unknown";
            this.position = "Unknown";
            System.out.println("Error: LoggedInIdentifier has an unexpected format: [" + identifier + "]");
        }

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblFullname = new javax.swing.JLabel();
        txtFullname = new javax.swing.JTextField();
        lblMyKad = new javax.swing.JLabel();
        txtMyKad = new javax.swing.JTextField();
        lblEmployeeID = new javax.swing.JLabel();
        txtEmployeeID = new javax.swing.JTextField();
        lblPhoneNo = new javax.swing.JLabel();
        txtPhoneNo = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        txtAddLine1 = new javax.swing.JTextField();
        txtAddLine2 = new javax.swing.JTextField();
        txtAddLine3 = new javax.swing.JTextField();
        txtAddLine4 = new javax.swing.JTextField();
        lblBankAcc = new javax.swing.JLabel();
        txtBankAcc = new javax.swing.JTextField();
        lblEmergency = new javax.swing.JLabel();
        txtEmergency = new javax.swing.JTextField();
        lblPosition = new javax.swing.JLabel();
        txtPosition = new javax.swing.JTextField();
        lblDepartment = new javax.swing.JLabel();
        txtDepartment = new javax.swing.JTextField();
        lblGrossSalary = new javax.swing.JLabel();
        txtGrossSalary = new javax.swing.JTextField();
        lblCompany = new javax.swing.JLabel();
        txtCompany = new javax.swing.JTextField();
        lblStartDate = new javax.swing.JLabel();
        txtStartDate = new javax.swing.JTextField();
        lblEndDate = new javax.swing.JLabel();
        txtEndDate = new javax.swing.JTextField();
        lblJobTitle = new javax.swing.JLabel();
        txtJobTitle = new javax.swing.JTextField();
        lblOverview = new javax.swing.JLabel();
        txtOverview = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblWorkExperinced = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        btnClear1 = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        mainPanel.setBackground(new java.awt.Color(231, 240, 220));
        mainPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));

        headerPanel.setBackground(new java.awt.Color(89, 116, 69));
        headerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(231, 240, 220));
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        headerPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(231, 240, 220));
        jLabel2.setText(" Employee Form");
        headerPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        lblFullname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFullname.setForeground(new java.awt.Color(72, 89, 4));
        lblFullname.setText("Fullname : ");

        txtFullname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtFullname.setForeground(new java.awt.Color(72, 89, 4));
        txtFullname.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));
        txtFullname.setName(""); // NOI18N
        txtFullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFullnameActionPerformed(evt);
            }
        });

        lblMyKad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMyKad.setForeground(new java.awt.Color(72, 89, 4));
        lblMyKad.setText("MyKad (NRIC) : ");

        txtMyKad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtMyKad.setForeground(new java.awt.Color(72, 89, 4));
        txtMyKad.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));
        txtMyKad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMyKadActionPerformed(evt);
            }
        });

        lblEmployeeID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmployeeID.setForeground(new java.awt.Color(72, 89, 4));
        lblEmployeeID.setText("EmployeeID : ");

        txtEmployeeID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtEmployeeID.setForeground(new java.awt.Color(72, 89, 4));
        txtEmployeeID.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));
        txtEmployeeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeIDActionPerformed(evt);
            }
        });

        lblPhoneNo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPhoneNo.setForeground(new java.awt.Color(72, 89, 4));
        lblPhoneNo.setText("Phone No. : ");

        txtPhoneNo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtPhoneNo.setForeground(new java.awt.Color(72, 89, 4));
        txtPhoneNo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));
        txtPhoneNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNoActionPerformed(evt);
            }
        });

        lblAddress.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAddress.setForeground(new java.awt.Color(72, 89, 4));
        lblAddress.setText("Address Home : ");

        txtAddLine1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtAddLine1.setForeground(new java.awt.Color(72, 89, 4));
        txtAddLine1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));
        txtAddLine1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddLine1ActionPerformed(evt);
            }
        });

        txtAddLine2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtAddLine2.setForeground(new java.awt.Color(72, 89, 4));
        txtAddLine2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));
        txtAddLine2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddLine2ActionPerformed(evt);
            }
        });

        txtAddLine3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtAddLine3.setForeground(new java.awt.Color(72, 89, 4));
        txtAddLine3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));
        txtAddLine3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddLine3ActionPerformed(evt);
            }
        });

        txtAddLine4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtAddLine4.setForeground(new java.awt.Color(72, 89, 4));
        txtAddLine4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));
        txtAddLine4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddLine4ActionPerformed(evt);
            }
        });

        lblBankAcc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBankAcc.setForeground(new java.awt.Color(72, 89, 4));
        lblBankAcc.setText("Bank Account No. : ");

        txtBankAcc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtBankAcc.setForeground(new java.awt.Color(72, 89, 4));
        txtBankAcc.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));
        txtBankAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBankAccActionPerformed(evt);
            }
        });

        lblEmergency.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmergency.setForeground(new java.awt.Color(72, 89, 4));
        lblEmergency.setText("Emergency Contact : ");

        txtEmergency.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtEmergency.setForeground(new java.awt.Color(72, 89, 4));
        txtEmergency.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));
        txtEmergency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmergencyActionPerformed(evt);
            }
        });

        lblPosition.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPosition.setForeground(new java.awt.Color(72, 89, 4));
        lblPosition.setText(" Position : ");

        txtPosition.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtPosition.setForeground(new java.awt.Color(72, 89, 4));
        txtPosition.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));
        txtPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPositionActionPerformed(evt);
            }
        });

        lblDepartment.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDepartment.setForeground(new java.awt.Color(72, 89, 4));
        lblDepartment.setText(" Department : ");

        txtDepartment.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtDepartment.setForeground(new java.awt.Color(72, 89, 4));
        txtDepartment.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));
        txtDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDepartmentActionPerformed(evt);
            }
        });

        lblGrossSalary.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGrossSalary.setForeground(new java.awt.Color(72, 89, 4));
        lblGrossSalary.setText(" Monthly Gross Salary : ");

        txtGrossSalary.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtGrossSalary.setForeground(new java.awt.Color(72, 89, 4));
        txtGrossSalary.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));
        txtGrossSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGrossSalaryActionPerformed(evt);
            }
        });

        lblCompany.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCompany.setForeground(new java.awt.Color(72, 89, 4));
        lblCompany.setText(" Company : ");

        txtCompany.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtCompany.setForeground(new java.awt.Color(72, 89, 4));
        txtCompany.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));
        txtCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCompanyActionPerformed(evt);
            }
        });

        lblStartDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblStartDate.setForeground(new java.awt.Color(72, 89, 4));
        lblStartDate.setText(" Start (DD/MM/YYYY) : ");

        txtStartDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtStartDate.setForeground(new java.awt.Color(72, 89, 4));
        txtStartDate.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));
        txtStartDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStartDateActionPerformed(evt);
            }
        });

        lblEndDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEndDate.setForeground(new java.awt.Color(72, 89, 4));
        lblEndDate.setText("End (DD/MM/YYYY) :  ");

        txtEndDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtEndDate.setForeground(new java.awt.Color(72, 89, 4));
        txtEndDate.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));
        txtEndDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEndDateActionPerformed(evt);
            }
        });

        lblJobTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblJobTitle.setForeground(new java.awt.Color(72, 89, 4));
        lblJobTitle.setText(" Job Title : ");

        txtJobTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtJobTitle.setForeground(new java.awt.Color(72, 89, 4));
        txtJobTitle.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));
        txtJobTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJobTitleActionPerformed(evt);
            }
        });

        lblOverview.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblOverview.setForeground(new java.awt.Color(72, 89, 4));
        lblOverview.setText("Overview of Leave Entitlement :");

        txtOverview.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtOverview.setForeground(new java.awt.Color(72, 89, 4));
        txtOverview.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));
        txtOverview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOverviewActionPerformed(evt);
            }
        });

        lblGender.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGender.setForeground(new java.awt.Color(72, 89, 4));
        lblGender.setText(" Gender (Male/Female) : ");

        txtGender.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtGender.setForeground(new java.awt.Color(72, 89, 4));
        txtGender.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));
        txtGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenderActionPerformed(evt);
            }
        });

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(72, 89, 4));
        lblUsername.setText("Username : ");

        txtUsername.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(72, 89, 4));
        txtUsername.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));
        txtUsername.setName(""); // NOI18N
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        lblWorkExperinced.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblWorkExperinced.setForeground(new java.awt.Color(72, 89, 4));
        lblWorkExperinced.setText("Work Experinced : ");

        btnRegister.setBackground(new java.awt.Color(89, 116, 69));
        btnRegister.setFont(new java.awt.Font("Bookman Old Style", 1, 16)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(231, 240, 220));
        btnRegister.setText("Submit");
        btnRegister.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));
        btnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegisterMouseClicked(evt);
            }
        });
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnClear1.setBackground(new java.awt.Color(89, 116, 69));
        btnClear1.setFont(new java.awt.Font("Bookman Old Style", 1, 16)); // NOI18N
        btnClear1.setForeground(new java.awt.Color(231, 240, 220));
        btnClear1.setText("Clear");
        btnClear1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));
        btnClear1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClear1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClear1MouseClicked(evt);
            }
        });
        btnClear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 987, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFullname, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFullname)
                    .addComponent(lblEmployeeID)
                    .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhoneNo)
                    .addComponent(txtPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmergency)
                    .addComponent(txtEmergency, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddress)
                    .addComponent(txtAddLine1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddLine3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddLine4, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnClear1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtBankAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtDepartment, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                            .addComponent(txtGender, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblGrossSalary, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblGender, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtGrossSalary)))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblBankAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(40, 40, 40)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(lblOverview)
                                        .addGap(0, 117, Short.MAX_VALUE))
                                    .addComponent(txtJobTitle)
                                    .addComponent(txtOverview)))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblPosition)
                                        .addComponent(txtPosition, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                        .addComponent(lblDepartment)
                                        .addComponent(txtMyKad))
                                    .addComponent(lblMyKad))
                                .addGap(40, 40, 40)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblStartDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtStartDate))
                                        .addGap(18, 18, 18)
                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(mainPanelLayout.createSequentialGroup()
                                                .addGap(0, 3, Short.MAX_VALUE)
                                                .addComponent(lblEndDate))
                                            .addComponent(txtEndDate)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                        .addComponent(lblCompany)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCompany))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblWorkExperinced)
                                            .addComponent(lblJobTitle))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFullname)
                    .addComponent(lblMyKad)
                    .addComponent(lblWorkExperinced))
                .addGap(5, 5, 5)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFullname, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCompany)
                    .addComponent(txtMyKad, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStartDate)
                    .addComponent(lblEndDate)
                    .addComponent(lblPosition)
                    .addComponent(lblUsername))
                .addGap(12, 12, 12)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmployeeID)
                            .addComponent(lblJobTitle)))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblDepartment)))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJobTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoneNo)
                    .addComponent(lblOverview)
                    .addComponent(lblGrossSalary))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtOverview, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGrossSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmergency)
                            .addComponent(lblGender))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmergency, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBankAcc)
                            .addComponent(lblAddress))
                        .addGap(14, 14, 14)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAddLine1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBankAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAddLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addComponent(txtAddLine3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAddLine4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear1ActionPerformed
        // TODO add your handling code here:
        // Clear all text fields
        txtFullname.setText("");
        txtMyKad.setText("");
        txtEmployeeID.setText("");
        txtPhoneNo.setText("");
        txtEmergency.setText("");
        txtAddLine1.setText("");
        txtAddLine2.setText("");
        txtAddLine3.setText("");
        txtAddLine4.setText("");
        txtBankAcc.setText("");
        txtPosition.setText("");
        txtDepartment.setText("");
        txtGrossSalary.setText("");
        txtGender.setText("");
        txtCompany.setText("");
        txtStartDate.setText("");
        txtEndDate.setText("");
        txtJobTitle.setText("");
        txtOverview.setText("");
        txtUsername.setText("");

    }//GEN-LAST:event_btnClear1ActionPerformed

    private void btnClear1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClear1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClear1MouseClicked

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMouseClicked
        // Validate all required fields
        if (txtEmployeeID.getText().isEmpty() || 
            txtUsername.getText().isEmpty() || 
            txtFullname.getText().isEmpty() || 
            txtMyKad.getText().isEmpty() || 
            txtPhoneNo.getText().isEmpty() || 
            txtEmergency.getText().isEmpty() || 
            txtAddLine1.getText().isEmpty() || 
            txtAddLine2.getText().isEmpty() || 
            txtAddLine3.getText().isEmpty() || 
            txtAddLine4.getText().isEmpty() || 
            txtBankAcc.getText().isEmpty() || 
            txtPosition.getText().isEmpty() || 
            txtDepartment.getText().isEmpty() || 
            txtGrossSalary.getText().isEmpty() || 
            txtGender.getText().isEmpty() || 
            txtCompany.getText().isEmpty() || 
            txtStartDate.getText().isEmpty() || 
            txtEndDate.getText().isEmpty() || 
            txtJobTitle.getText().isEmpty() || 
            txtOverview.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Please fill in all required fields before proceeding.");
            return; // Stop execution if any field is empty
        }

        // Generate password using RegisterManager
        String password = registerManager.generateNextPassword();

        Employee employee = new Employee();
        employee.setEmployeeID(txtEmployeeID.getText());
        employee.setUsername(txtUsername.getText());
        employee.setFullname(txtFullname.getText());
        employee.setMyKad(txtMyKad.getText());
        employee.setPhoneno(txtPhoneNo.getText());
        employee.setEmergency(txtEmergency.getText());
        employee.setAddLine1(txtAddLine1.getText());
        employee.setAddLine2(txtAddLine2.getText());
        employee.setAddLine3(txtAddLine3.getText());
        employee.setAddLine4(txtAddLine4.getText());
        employee.setBankAcc(txtBankAcc.getText());
        employee.setPosition(txtPosition.getText());
        employee.setDepartment(txtDepartment.getText());
        employee.setGrossSalary(txtGrossSalary.getText());
        employee.setGender(txtGender.getText());
        employee.setCompany(txtCompany.getText());
        employee.setStartDate(txtStartDate.getText());
        employee.setEndDate(txtEndDate.getText());
        employee.setJobTitle(txtJobTitle.getText());
        employee.setOverview(txtOverview.getText());

        boolean success = registerManager.registerEmployee(employee, password);

        if (success) {
            JOptionPane.showMessageDialog(null, "Registration successful");
            this.dispose();

            AdminPage adminPage = new AdminPage(employee.getEmployeeID());
            adminPage.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Error registering employee.");
        }
    }//GEN-LAST:event_btnRegisterMouseClicked

    private void txtGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenderActionPerformed

    private void txtOverviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOverviewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOverviewActionPerformed

    private void txtJobTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJobTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJobTitleActionPerformed

    private void txtEndDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEndDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEndDateActionPerformed

    private void txtStartDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStartDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStartDateActionPerformed

    private void txtCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCompanyActionPerformed

    private void txtGrossSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGrossSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGrossSalaryActionPerformed

    private void txtDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDepartmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDepartmentActionPerformed

    private void txtPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPositionActionPerformed

    private void txtEmergencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmergencyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmergencyActionPerformed

    private void txtBankAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBankAccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBankAccActionPerformed

    private void txtAddLine4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddLine4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddLine4ActionPerformed

    private void txtAddLine3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddLine3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddLine3ActionPerformed

    private void txtAddLine2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddLine2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddLine2ActionPerformed

    private void txtAddLine1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddLine1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddLine1ActionPerformed

    private void txtPhoneNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNoActionPerformed

    private void txtEmployeeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeIDActionPerformed

    private void txtMyKadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMyKadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMyKadActionPerformed

    private void txtFullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFullnameActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        // Dispose the userAccForm frame
        this.dispose();

        // Open AdminTest frame
        AdminPage adminPage = new AdminPage("exampleIdentifier:Position"); // Pass identifier to AdminPage
        adminPage.setVisible(true);
        adminPage.pack();
        adminPage.setLocationRelativeTo(null);
        adminPage.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear1;
    private javax.swing.JButton btnRegister;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBankAcc;
    private javax.swing.JLabel lblCompany;
    private javax.swing.JLabel lblDepartment;
    private javax.swing.JLabel lblEmergency;
    private javax.swing.JLabel lblEmployeeID;
    private javax.swing.JLabel lblEndDate;
    private javax.swing.JLabel lblFullname;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblGrossSalary;
    private javax.swing.JLabel lblJobTitle;
    private javax.swing.JLabel lblMyKad;
    private javax.swing.JLabel lblOverview;
    private javax.swing.JLabel lblPhoneNo;
    private javax.swing.JLabel lblPosition;
    private javax.swing.JLabel lblStartDate;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblWorkExperinced;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField txtAddLine1;
    private javax.swing.JTextField txtAddLine2;
    private javax.swing.JTextField txtAddLine3;
    private javax.swing.JTextField txtAddLine4;
    private javax.swing.JTextField txtBankAcc;
    private javax.swing.JTextField txtCompany;
    private javax.swing.JTextField txtDepartment;
    private javax.swing.JTextField txtEmergency;
    private javax.swing.JTextField txtEmployeeID;
    private javax.swing.JTextField txtEndDate;
    private javax.swing.JTextField txtFullname;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtGrossSalary;
    private javax.swing.JTextField txtJobTitle;
    private javax.swing.JTextField txtMyKad;
    private javax.swing.JTextField txtOverview;
    private javax.swing.JTextField txtPhoneNo;
    private javax.swing.JTextField txtPosition;
    private javax.swing.JTextField txtStartDate;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
